name: SNCrypto Web PR Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - 'packages/sncrypto-web/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build
        run: yarn build:sncrypto-web
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build SNJS Docker image for testing
        run: |
          yarn docker build @standardnotes/sncrypto-web -t standardnotes/sncrypto-web:${{ github.sha }}
          docker push standardnotes/sncrypto-web:${{ github.sha }}
          docker tag standardnotes/sncrypto-web:${{ github.sha }} standardnotes/sncrypto-web:test
          docker push standardnotes/sncrypto-web:test
      - name: Run E2E test suite
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: standardnotes
          repo: e2e
          github_token: ${{ secrets.CI_PAT_TOKEN }}
          workflow_file_name: sncrypto-web.yml
          wait_interval: 30
          client_payload: '{"image_tag": "${{ github.sha }}"}'
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true
